# Generated by Django 5.1.3 on 2024-12-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='reader',
            new_name='user',
        ),
    ]
